services:
  rasa:
    image: rasa/rasa:3.6.21-full
    ports:
      - "5003:5003"
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - -p
      - "5003"
    # environment:
    #   - SANIC_NO_UVLOOP=true
    # Link the action server
    depends_on:
      - action_server
  action_server:
    image: rasa/rasa-sdk:3.6.2
    volumes:
      - ./actions:/app/actions
    command:
      - start
      - --actions
      - actions
      - -p
      - "5056"
    expose:
      - "5056"
