services:
  rasa:
    image: rasa/rasa:3.6.21-full
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command:
      - run
    # Link the action server
    depends_on:
      - action_server
  action_server:
    image: rasa/rasa-sdk:3.6.2
    volumes:
      - ./actions:/app/actions
    expose:
      - "5055"
